### ISSUE TITLE
创建了活动，但是无法使用，这是怎么回事呢

### ISSUE THREAD

**Issue by solider245** [jki14/meeting-horn#5]
我在游戏里创建活动，显示创建活动成功了，但是集结号看不到我创建的活动

**Comment by jki14** [comment]
首先申明：我不是插件原作者也不是插件在NGA论坛的发布者。
感谢你在这里反馈issue，请问方便提供进一步内容以便我尝试定位Root Cause么？

**Comment by jki14** [comment]
Close the issue since no follow-up in 12 days.
